# Welcome to Jekyll!

# Website settings
title: "J.Fallt"
description: "Personal website of Jared Fallt"
keywords: "jfallt"
baseurl: "/"
url: "http://jfallt.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Fallt'
  first_name: 'Jared'
  last_name: 'Fallt'
  email: 'fallt.jared@gmail.com'
  linkedin_username: 'https://www.linkedin.com/in/jared-fallt/'
  github_username: 'jfallt'
  head_img: 'https://media.licdn.com/dms/image/v2/C4D03AQHmS71oQYcWUw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1588615484562?e=1758153600&v=beta&t=5WvvZIRbmpZuZxDQ5xOxn6rZAydlRMQCby70wPs1qb0'
  desc: "Currently I am a senior data engineer at Macquarie Group. My work include developing reusable best practices for data ingestion, performance tuning pipelines and building appication MVPs" 

  

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
